### ISSUE TITLE
Mask Annotator is not receiving color_map='index'

### ISSUE THREAD

**Issue by NandiniLReddy** [roboflow/supervision#523] opened 2023-10-23 21:20 UTC
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

sv.MaskAnnotator, previously was working well; Now it's rasing an error saying color_map="index" is an unexpected keyword.

### Additional

`mask_annotator = sv.MaskAnnotator(color_map='index')

detections = sv.Detections.from_sam(sam_result=sam_result)

annotated_image = mask_annotator.annotate(scene=image_bgr.copy(), detections=detections)

sv.plot_images_grid(
    images=[image_bgr, annotated_image],
    grid_size=(1, 2),
    titles=['source image', 'segmented image']
)`

Error:
`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-17-89adae8df538>](https://localhost:8080/#) in <cell line: 1>()
----> 1 mask_annotator = sv.MaskAnnotator(color_map='index')
      2 
      3 detections = sv.Detections.from_sam(sam_result=sam_result)
      4 
      5 annotated_image = mask_annotator.annotate(scene=image_bgr.copy(), detections=detections)

TypeError: MaskAnnotator.__init__() got an unexpected keyword argument 'color_map'`

**Comment by onuralpszr** [comment] 2023-10-23 21:51
Duplicate of #509 

Solution : https://github.com/roboflow/supervision/issues/509#issuecomment-1773704180

**Closed by onuralpszr** 2023-10-23 21:51 UTC
Labels: question

**Comment by SkalskiP** [comment] 2023-10-23 22:24
@NandiniLReddy just update your mask annotator to `mask_annotator = sv.MaskAnnotator(color_lookup = sv.ColorLookup.INDEX)` and you should be good to go!

**Comment by NandiniLReddy** [comment] 2023-11-02 23:34
@SkalskiP Thank you! I was able to solve it. 
Instead of the Bounding box as a prompt, can I use Text sequence as a prompt to segment? 

Thank you!
