### ISSUE TITLE
[Q. Is there a limit at the frame? ]

### ISSUE THREAD

**Issue by YooSeungHo0124** [roboflow/supervision#356] opened 2023-09-05 06:51 UTC
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

Hi 
i tried to test line counting with my video
when i tried to test with 30 frames for 1 sec  =>  works!
but 0.5  frame for 1 sec video => doesn't make result video

<img width="360" alt="image" src="https://github.com/roboflow/supervision/assets/126686058/ad330402-b53a-4c89-9a28-e46c4fa5bc6c">

but still detecting cars

somebody help me ! ;)

**Comment by hardikdava** [comment] 2023-09-05 17:49
@YooSeungHo0124 Can you provide us colab notebook or code to reproduce your issue? Please let us know in detail about the issue.

**Comment by hardikdava** [comment] 2023-09-06 15:21
@YooSeungHo0124 If I understood you correctly then current `sv.get_video_frames_generator` supports based on `stride` and minimum value you can use is `1`. You have to calculate `stride` based on you numbers of frames in your video. The logic is that if you have `stride=1` then it will read every frames from video, if you have `stride=2` then function will read every second frame from the video.

**Comment by onuralpszr** [comment] 2023-09-18 11:06
It is been a 2 weeks since issue opened and I assume problem solved and closing the issue. 

Thank you  👍

**Closed by onuralpszr** 2023-09-18 11:06 UTC
Labels: question
