### ISSUE TITLE
AttributeError: module 'supervision' has no attribute 'TraceAnnotator'

### ISSUE THREAD

**Issue by hoongyuan** [roboflow/supervision#568] opened 2023-11-03 04:26 UTC
- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Problem

I was trying to follow the video: 'Traffic Analysis with YOLOv8 and ByteTrack - Vehicle Detection and Tracking' to implement the Trace Annotator on my project. But somehow I have this error output "AttributeError: module 'supervision' has no attribute 'TraceAnnotator'". 

I thought that TraceAnnotator() was already added into supervision 0.15.0? 

## Supervision version
<img width="797" alt="Screenshot 2023-11-03 at 12 23 26 PM" src="https://github.com/roboflow/supervision/assets/62897998/614e0aac-fff1-4538-97fc-93714a580956">
<img width="844" alt="Screenshot 2023-11-03 at 12 23 35 PM" src="https://github.com/roboflow/supervision/assets/62897998/a5c441a4-09f2-4551-94a7-ba6674e35718">

## Error Output
<img width="857" alt="Screenshot 2023-11-03 at 12 24 03 PM" src="https://github.com/roboflow/supervision/assets/62897998/fbbfc14e-15ae-4be2-999c-43aa8945bb82">

**Comment by SkalskiP** [comment] 2023-11-03 11:41
Hi, @hoongyuan 👋🏻 

The problem is not with Supervision but with Google Colab. If you import a package in Colab with package version `X` and then update the package to version `Y`, your already imported version will not get auto-updated from `X` to `Y`. You must restart the Python environment to access package version `Y`.

You can even observe this in your first screenshot. The last two lines say that you have successfully installed version `0.16.0` and that your current version is `0.2.0`.

I recommend that you fire up the notebook again, don't install version `0.2.0` but install `0.16.0` right away, and all should be well.

Closing issue. Feel free to reopen it if you encounter further problems. Good luck! 🤞🏻

**Closed by SkalskiP** 2023-11-03 11:41 UTC
Labels: question
