### ISSUE TITLE
Exported YOLOv8 Segmentation Data (OBB) Not Matching Annotations

### ISSUE THREAD

**Issue by Pavankunchala** [roboflow/supervision#1576] opened 2024-10-05 00:37 UTC
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

Description:
I am using Roboflow as the annotation tool for labeling images for YOLOv8-segmentation. However, the issue I am encountering is that the exported annotations (OBB format) do not match the annotations I created in the Roboflow interface. The segmentation points and bounding boxes seem misaligned or improperly exported, which is causing issues with model training and leading to inaccurate results.

Steps to Reproduce:
Annotate images for YOLOv8-segmentation using Roboflow.
Export the dataset in OBB (Oriented Bounding Box) format.
Compare the exported annotations with the annotations as seen in the Roboflow tool.
Expected Behavior:
The exported annotations should exactly match the annotations created in the Roboflow app, ensuring consistency between what was labeled and the exported data.

Actual Behavior:
The exported annotations are misaligned or inaccurate, and they do not reflect the original annotations created within the Roboflow tool. This is impacting the quality of the dataset and, consequently, my model training.

Impact:
The mismatched annotations lead to poor model performance as the training data is inconsistent with the actual labeled objects.
The segmentation results during inference are inaccurate due to improper training data.

![Figure_1](https://github.com/user-attachments/assets/aed8666b-2908-4180-8334-83f2e0cb0dc1)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by onuralpszr** [comment] 2024-10-06 01:27
@Pavankunchala hello I understand that you have problem `roboflow platform` itself not the supervision ? Based on what I understand I am closing this issue because it is not a bug for `supervision` but you can ask in roboflow support or discord channel to find better answer related to this case I hope that will help you out, If I am wrong please re-open the issue and explain and sharing minimal google collab would be nice as well.


Thank you.

**Closed by onuralpszr** 2024-10-06 01:27 UTC
Labels: bug
