### ISSUE TITLE
Cost Matrix contains NaN in ByteTrack() code 

### ISSUE THREAD

**Issue by tobieabel** [roboflow/supervision#458] opened 2023-10-12 10:34 UTC
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

I got the following error message when using supervision ByteTrack().  Something in the image is causing a NaN value to appear in the cost matrix in matching.py.  I have got around the issue for now by inserting the below line of code in bold to remove the NaN value from the matrix in line 32 of matching.py:

    cost_matrix[cost_matrix > thresh] = thresh +  1e-4
    **cost_matrix = np.nan_to_num(cost_matrix)**
    row_ind, col_ind = linear_sum_assignment(cost_matrix)
    indices = np.column_stack((row_ind, col_ind))

console output:

/Users/tobieabel/PycharmProjects/Demo_4_Fight_and_Fall/venv/lib/python3.11/site-packages/supervision/detection/utils.py:56: RuntimeWarning: invalid value encountered in divide
  return area_inter / (area_true[:, None] + area_detection - area_inter)
Traceback (most recent call last):
  File "/Users/tobieabel/PycharmProjects/Demo_4_Fight_and_Fall/Main.py", line 192, in <module>
    start()
  File "/Users/tobieabel/PycharmProjects/Demo_4_Fight_and_Fall/Main.py", line 171, in start
    obj_detections, class_results, Incident = start.Run_Models(frame)
                                              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tobieabel/PycharmProjects/Demo_4_Fight_and_Fall/Main.py", line 76, in Run_Models
    obj_detections = self.tracker.update_with_detections(obj_detections)  # pass the detections through the tracker to add tracker ID as additional field to detections object
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tobieabel/PycharmProjects/Demo_4_Fight_and_Fall/venv/lib/python3.11/site-packages/supervision/tracker/byte_tracker/core.py", line 235, in update_with_detections
    tracks = self.update_with_tensors(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tobieabel/PycharmProjects/Demo_4_Fight_and_Fall/venv/lib/python3.11/site-packages/supervision/tracker/byte_tracker/core.py", line 367, in update_with_tensors
    matches, u_unconfirmed, u_detection = matching.linear_assignment(
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tobieabel/PycharmProjects/Demo_4_Fight_and_Fall/venv/lib/python3.11/site-packages/supervision/tracker/byte_tracker/matching.py", line 33, in linear_assignment
    row_ind, col_ind = linear_sum_assignment(cost_matrix)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: matrix contains invalid numeric entries

### Environment

 - Supervision v0.15.0
 - Python 3.11

### Minimal Reproducible Example

I'm using the following code to run YOLO8 object detector through supervision to plot the tracking on the annotated frame

def Run_Models(self,frame:np.ndarray) ->sv.detection:
        obj_det_result = self.object_det_model.predict(frame, device = "mps", verbose = False, conf=0.4,iou=0.7)[0]#send every frame to YOLO model
        obj_detections = sv.Detections.from_ultralytics(obj_det_result)  # pass the results from the model to the sv libary as they are easier to manipulate
        obj_detections= obj_detections[obj_detections.class_id == 0]  # filter the list of detections so it only shows category '0' which is people
        obj_detections = self.tracker.update_with_detections(obj_detections)  # pass the detections through the tracker to add tracker ID as additional field to detections object

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment] 2023-10-12 10:48
Hi @tobieabel 👋🏻 Thanks for reporting the issue. Is it possible for you to provide us with a video example that we could use for debugging?

**Comment by tobieabel** [comment] 2023-11-02 15:36
Sorry for the late reply, the video is attached, but I think the issue may have been caused by the object detector I was using at the time, which was the standard YOLOv8n model.  Once I retrained it to get better detection results the issue seemed to go away.

https://github.com/roboflow/supervision/assets/34671814/8d7cf557-f70c-4f5d-9a0d-867bad690b59

**Comment by tobieabel** [comment] 2023-11-02 15:37
Sorry I can't attached a much longer video - the size is too large

**Comment by SkalskiP** [comment] 2024-01-26 08:59
Hi @tobieabel 👋🏻 Does this problem still occur?

**Comment by tobieabel** [comment] 2024-01-26 12:28
no, it was only that one time.  When I use a better performing model the tracking doesn't suffer from that problem anymore

**Comment by SkalskiP** [comment] 2024-05-07 11:06
@rolson24, do you have any idea what could be the cause of this old issue?

**Comment by rolson24** [comment] 2024-05-07 13:56
Hi @SkalskiP
Based on the warning at the beginning of the console output: 
```
/Users/tobieabel/PycharmProjects/Demo_4_Fight_and_Fall/venv/lib/python3.11/site-packages/supervision/detection/utils.py:56: RuntimeWarning: invalid value encountered in divide
return area_inter / (area_true[:, None] + area_detection - area_inter)
```
The only thing I can think of is that the bounding boxes coming from the YOLO model were either NaN, or they were bounding boxes that had 0 area. I'm leaning towards the boxes likely having 0 area (either the width is 0 or the height is 0) because I doubt Ultralytics would return boxes with null coordinates, but they might have returned boxes with 0 area.

I think the best option to possibly fix this is to simply set all of the NaN values to a cost value above the match threshold in the linear_assignment function. This would keep all of the detections around, but just not match any of the 0 area detections with any existing tracks. Then these 0 area detections, could get initialized as new tracks.
Alternatively, we could just filter them right away at the beginning of update_with_tensors by calculating the area of each bounding box and then filtering out the ones with 0 area.

**Comment by SkalskiP** [comment] 2024-05-08 11:35
Thanks @rolson24 🙏🏻 I think that bounding boxes with zero area are the most likely scenario. Would you be interested in writing a PR that would protect us from this?

**Comment by rolson24** [comment] 2024-05-08 14:40
@SkalskiP Sure!

**Comment by SkalskiP** [comment] 2024-05-08 14:45
@rolson24 thanks 🙏🏻

**Comment by LinasKo** [comment] 2024-06-14 13:13
Closing the issue as this is fixed.

**Closed by LinasKo** 2024-06-14 13:13 UTC
Labels: bug
