### ISSUE TITLE
Custom Symbol Annotators

### ISSUE THREAD

**Issue by mhsmathew** [roboflow/supervision#1450] opened 2024-08-15 02:16 UTC
### Search before asking

- [x] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

A way to add custom symbols of annotators onto the image. Or possibly even other images.

### Use case

I want to be able to annotator multiple classes of objects with different symbols, like Xs and Os.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by LinasKo** [comment] 2024-08-15 08:20
Hi @mhsmathew 👋 

This is a duplicate of #460, so I'll close this.

Good reminder that we still don't have this functionality - I'll ping you when we deploy it.

**Closed by LinasKo** 2024-08-15 08:20 UTC
Labels: enhancement

**Comment by LinasKo** [comment] 2024-08-27 10:54
Hi @mhsmathew, the new supervision release tomorrow shall include `IconAnnotator`. Feel free to try it out when you have the time :)
