### ISSUE TITLE
opencv-headless requirement breaks existing installation

### ISSUE THREAD

**Issue by adrianboguszewski** [roboflow/supervision#351] opened 2023-09-04 15:43 UTC
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

Supervision >= 0.12.0 requires opencv-headless. If I use opencv-python in my application and then install supervision, my opencv is broken (overwritten by the headless package).
It would be nice to configure it somehow not to install opencv-headless if any opencv package already installed.

### Environment

This happens for supervision >= 0.12.0
Ubuntu 22.04
Python 3.10

### Minimal Reproducible Example

pip install opencv-python
pip install supervision==0.14.0

import cv2
import numpy as np
arr = np.zeros((10, 10), dtype=np.uint8)
cv2.imshow("img", arr)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by onuralpszr** [comment] 2023-09-04 16:24
@adrianboguszewski  for workaround you can delete headless and reinstall full and use with full version and that would work.  I can make them explicitly separated and ask install one of them but if you just install supervision it won't have any opencv so we can change our install to force either let's say "headless" and "full"  like "pip install supervision[full]" but If you also try to install headless it will skip supervision but install headless in the of the day. So in the end of the day user also has to choose one of them and make sure not have both or delete one them.

**Comment by adrianboguszewski** [comment] 2023-09-05 09:52
Yeah, that's what I did as a workaround. But also, I'm thinking about the mature solution. I don't know if there is any way to check opencv has been already installed so more research is needed.

I think your proposition isn't bad. Let's say the default version is headless and if the user wants to have full opencv they must go with pip install supervision[full]

**Comment by onuralpszr** [comment] 2023-09-05 09:54
> I think your proposition isn't bad. Let's say the default version is headless and if the user wants to have full opencv they must go with pip install supervision[full]

That is the default right now. But problem is full bring headless too.

**Comment by onuralpszr** [comment] 2023-09-05 10:12
Also related : https://github.com/python-poetry/poetry/issues/6419 and not exist yet. So most possible option I see separate both and install one but user has to delete if there is both and we need to as a warning sign as well.

**Comment by onuralpszr** [comment] 2023-09-05 10:14
@SkalskiP  I know how we do it. So I think we should document at least for conflict problem between headless and full and maybe we can reconsider separate but warning is clear (just install "pip install supervision" won't be enough anymore.

**Comment by onuralpszr** [comment] 2023-09-05 17:21
@hardikdava  could you please put your input as well ? I am thinking about 2 ways but I wanna talk through as well.

**Comment by hardikdava** [comment] 2023-09-05 17:34
@onuralpszr I would suggest to do as following:

```
Install supervision with normal opencv package:
pip install supervision  

Install supervision with opencv-headless
pip install supervision[headless]
```

**Comment by onuralpszr** [comment] 2023-09-05 17:40
that is the current but problem is they need to delete headless if they started like that*

**Comment by SkalskiP** [comment] 2023-10-18 19:38
@onuralpszr is that problem still active?

**Comment by Buckler89** [comment] 2024-07-31 13:39
> @onuralpszr is that problem still active?

yes

**Comment by onuralpszr** [comment] 2024-07-31 13:47
> > @onuralpszr is that problem still active?
> 
> yes. For me the solution suggested by @dennis-ciancoders broke imshow and waitKey methods of opencv.
> 
> Someoneelse is encountering the same issue?

Quick workaround 

```bash
pip install supervision
pip uninstall opencv-python-headless
pip install opencv-python

```

This should work. You uninstall headless and install full one and you can make it work. Make sure you delete headless and install opencv-python, If somehow you have both installed then delete both and install "opencv-python" should work. Let me know how is it go.

**Comment by SkalskiP** [comment] 2024-08-06 09:33
Hi @onuralpszr 👋🏻 Do we have any ideas on how to improve `desktop` / `headless` installs? If not, I suggest we close this issue.

**Comment by onuralpszr** [comment] 2024-08-06 10:04
> Hi @onuralpszr 👋🏻 Do we have any ideas on how to improve `desktop` / `headless` installs? If not, I suggest we close this issue.

@SkalskiP hello 👋 

2 suggestions, I will explicit documentation how to manage properly those cases and not do change on toml, second I will remove headless and put desktop package and I will wrote documentation again to how to switch between them and explain how to manage desktop and headless, based on these I can create pr and we can put marl as complete?

**Comment by SkalskiP** [comment] 2024-08-07 11:06
Sounds good. Would you like to work on this PR?

**Comment by onuralpszr** [comment] 2024-08-07 11:31
> Sounds good. Would you like to work on this PR?

Sure let me write based on option one then ?

**Comment by tkelestemur-bdai** [comment] 2024-09-16 23:34
Hello, has there been any update on this? I'm trying to use opencv functions alongside the supervision but that's impossible because headless opencv is overwriting cv2 functions. For example, I can't run `cv.imshow(...)`. If I uninstall opencv-python-headless, then I'm getting the following error:

```
(vpl) tkelestemur_theaiinstitute_com@tkelestemur-ubuntu2204-l4x1-1024gb:~/visuomotor/visuomotor/perception$ python samv2.py
Traceback (most recent call last):
  File "/home/tkelestemur_theaiinstitute_com/visuomotor/visuomotor/perception/samv2.py", line 8, in <module>
    import supervision as sv
  File "/home/tkelestemur_theaiinstitute_com/venvs/vpl/lib/python3.10/site-packages/supervision/__init__.py", line 9, in <module>
    from supervision.annotators.core import (
  File "/home/tkelestemur_theaiinstitute_com/venvs/vpl/lib/python3.10/site-packages/supervision/annotators/core.py", line 21, in <module>
    from supervision.draw.utils import draw_polygon
  File "/home/tkelestemur_theaiinstitute_com/venvs/vpl/lib/python3.10/site-packages/supervision/draw/utils.py", line 164, in <module>
    text_font: int = cv2.FONT_HERSHEY_SIMPLEX,
AttributeError: module 'cv2' has no attribute 'FONT_HERSHEY_SIMPLEX'
```

**Comment by LinasKo** [comment] 2024-09-18 09:06
We'll look into it this release. It's about time we fixed it.

**Comment by onuralpszr** [comment] 2024-09-19 14:54
[#1530 ](https://github.com/roboflow/supervision/pull/1530) merged and close as complete

**Closed by onuralpszr** 2024-09-19 14:54 UTC
Labels: bug, question

**Comment by LinasKo** [comment] 2024-09-19 15:33
Hi @tkelestemur-bdai,

The issue is fixed on development branch. You can install it with `pip install git+https://github.com/roboflow/supervision.git@develop`.

This will be added to the main package in the next release, at around 4th of October.

**Comment by Kutayykilic** [comment] 2024-10-22 07:32
> Hi @tkelestemur-bdai,
> 
> The issue is fixed on development branch. You can install it with `pip install git+https://github.com/roboflow/supervision.git@develop`.
> 
> This will be added to the main package in the next release, at around 4th of October.



So about that, while on a pre existing environment that I was using, (ultralytics docker image), installing supervision on that docker image makes opencv break again, (circular import errors) and cv2.HERSHEY etc. 

I dealt with this a few months ago as well, the best solution was to install supervision without any extra dependencies, `pip install supervision --no-deps ` solved all the issues for me, except that you have to only install defused xml by yourself. I am sharing this comment in case if anyone needs it

**Comment by LinasKo** [comment] 2024-10-22 10:51
Thank you @Kutayykilic !
